model: llama-3.1-8b-instant
# model: llama-3.2-90b-text-preview
# max_tokens: 8192
# model: llama-3.1-70b-versatile
max_tokens: 8000

temperature: 1

platform: "github"

# Gitlab config
gitlab_url: "https://gitlab.com"
gitlab_project: "danielratmiroff%2Fgai"
gitlab_assignee_id: 10437754
target_branch: "master"

# GitHub config
github_owner: "Danielratmiroff"
github_repo: "gai"
